* roll - A project for parsing and working with dice.

It's exactly what it says on the tin. This library
provides two base primitives for rolling dice. One which
can translate strings in the form ~<count>d<sides><modifier>~
into actual rolls generated by a random number generator.

If you want to control/reseed the library, use =rand.Seed()=
function.

** Architecture

*** Roller Interface

One layer above the Roll primitives we provide the Roller interface
which allows the user to pass in a ~formula.Formula~. It also
introduces the ~Extensions~ interface. Which allows for additional
meta information to be added to a roll result such as identifying
if the roll is a critical roll, or returning the sum of all the rolls.

*** Roll Primitives

#+BEGIN_SRC plantuml

#+END_SRC

The library is broken down into two parts. The rolling and the
formula. The rolling library functions provide the rolling
primitives =Roll(int) int= and =RollN(int, int) int=. Which roll
a single die and multiple dice respectively.

*** Formula Interface

A roll formula is just an algebraic way of defining some dice to roll a
valid formula will be in the form ~<count>'d'<sides><modifier>~ where
words surrounded by a less-than and a greater-than symbol are parameters
and those surrounded by single quotes are literal strings.

Those parameters are defined as follows:

- count :: A signed integer that defines the number of dice to roll. The count is optional and is considered to be ~1~ by default.
- sides :: A signed integer that defines the number of sides on each die.
- modifier :: An unsigned integer. Though optional when used the sign (either ~+~ or ~-~) must prefix the value. (e.g. ~+23~ or ~-23~)

This interface provides the =RollWithFormula(formula.Formula) (FormulaRoll, error)=
[[file:roller.go::13][function]] which will take a formula and return a ~FormulaRoll~.
A FormulaRoll contains the formula passed in, the result of the rolls, and any
messages provided by extensions.

*** Extensions Interface

The extension interface allows the programmer to add additional information 
to the result of a roll. 
